name: CI Java

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '17.0.8'
      - name: Build with Maven
        run:  mvn -B package --file pom.xml